#ifndef __MAIN_PHP_EXIT_CODES_H__
#define __MAIN_PHP_EXIT_CODES_H__

enum PHP_EXIT_CODES {
  // exit called from main/main.c
  PHP_MODULE_INITIALIZATION_FAILED = 100,
  PHP_MODULE_STARTUP_FAILED = 101,

  // exit called from zend_alloc.c
  ZEND_MM_PANIC = 110,
  ZEND_INVALID_BLOCK_SIZE = 111,
  ZEND_CANNOT_INIT_STORAGE = 112,
  ZEND_CANNOT_ALLOC_HEAP = 113,
  ZEND_UNSUPPORTED_STORAGE_TYPE = 114,
  ZEND_INVALID_MM_SEG_SIZE = 115,
  ZEND_SMALL_MM_SEG_SIZE = 116,
  ZEND_BAILOUT = 117,

  // exit called from ext/mbstring/oniguruma/enc/mktable.c
  MBSTRING_MKTABLE_1 = 130,
  MBSTRING_MKTABLE_2 = 131,
  MBSTRING_MKTABLE_3 = 132,
  MBSTRING_MKTABLE_4 = 133,
  MBSTRING_MKTABLE_5 = 134,
  MBSTRING_MKTABLE_6 = 135,
  MBSTRING_MKTABLE_7 = 136,
  MBSTRING_MKTABLE_8 = 137,
  MBSTRING_MKTABLE_9 = 138,
  MBSTRING_MKTABLE_10 = 139,
};

#endif  // __MAIN_PHP_EXIT_CODES_H__

