#include "third_party/libmcrypt/lib/mcrypt_internal.h"

/* This is automatically created. Don't touch... */

extern cbc_LTX__init_mcrypt();
extern cbc_LTX__mcrypt_set_state();
extern cbc_LTX__mcrypt_get_state();
extern cbc_LTX__end_mcrypt();
extern cbc_LTX__mcrypt();
extern cbc_LTX__mdecrypt();
extern cbc_LTX__has_iv();
extern cbc_LTX__is_block_mode();
extern cbc_LTX__is_block_algorithm_mode();
extern cbc_LTX__mcrypt_get_modes_name();
extern cbc_LTX__mcrypt_mode_get_size();
extern cbc_LTX__mcrypt_mode_version();
extern cfb_LTX__init_mcrypt();
extern cfb_LTX__mcrypt_set_state();
extern cfb_LTX__mcrypt_get_state();
extern cfb_LTX__end_mcrypt();
extern cfb_LTX__mcrypt();
extern cfb_LTX__mdecrypt();
extern cfb_LTX__has_iv();
extern cfb_LTX__is_block_mode();
extern cfb_LTX__is_block_algorithm_mode();
extern cfb_LTX__mcrypt_get_modes_name();
extern cfb_LTX__mcrypt_mode_get_size();
extern cfb_LTX__mcrypt_mode_version();
extern ctr_LTX__init_mcrypt();
extern ctr_LTX__mcrypt_set_state();
extern ctr_LTX__mcrypt_get_state();
extern ctr_LTX__end_mcrypt();
extern ctr_LTX__mcrypt();
extern ctr_LTX__mdecrypt();
extern ctr_LTX__has_iv();
extern ctr_LTX__is_block_mode();
extern ctr_LTX__is_block_algorithm_mode();
extern ctr_LTX__mcrypt_get_modes_name();
extern ctr_LTX__mcrypt_mode_get_size();
extern ctr_LTX__mcrypt_mode_version();
extern ecb_LTX__mcrypt_set_state();
extern ecb_LTX__mcrypt_get_state();
extern ecb_LTX__init_mcrypt();
extern ecb_LTX__end_mcrypt();
extern ecb_LTX__mcrypt();
extern ecb_LTX__mdecrypt();
extern ecb_LTX__has_iv();
extern ecb_LTX__is_block_mode();
extern ecb_LTX__is_block_algorithm_mode();
extern ecb_LTX__mcrypt_get_modes_name();
extern ecb_LTX__mcrypt_mode_get_size();
extern ecb_LTX__mcrypt_mode_version();
extern ncfb_LTX__init_mcrypt();
extern ncfb_LTX__mcrypt_set_state();
extern ncfb_LTX__mcrypt_get_state();
extern ncfb_LTX__end_mcrypt();
extern ncfb_LTX__mcrypt();
extern ncfb_LTX__mdecrypt();
extern ncfb_LTX__has_iv();
extern ncfb_LTX__is_block_mode();
extern ncfb_LTX__is_block_algorithm_mode();
extern ncfb_LTX__mcrypt_get_modes_name();
extern ncfb_LTX__mcrypt_mode_get_size();
extern ncfb_LTX__mcrypt_mode_version();
extern nofb_LTX__init_mcrypt();
extern nofb_LTX__mcrypt_set_state();
extern nofb_LTX__mcrypt_get_state();
extern nofb_LTX__end_mcrypt();
extern nofb_LTX__mcrypt();
extern nofb_LTX__mdecrypt();
extern nofb_LTX__has_iv();
extern nofb_LTX__is_block_mode();
extern nofb_LTX__is_block_algorithm_mode();
extern nofb_LTX__mcrypt_get_modes_name();
extern nofb_LTX__mcrypt_mode_get_size();
extern nofb_LTX__mcrypt_mode_version();
extern ofb_LTX__init_mcrypt();
extern ofb_LTX__mcrypt_set_state();
extern ofb_LTX__mcrypt_get_state();
extern ofb_LTX__end_mcrypt();
extern ofb_LTX__mcrypt();
extern ofb_LTX__mdecrypt();
extern ofb_LTX__has_iv();
extern ofb_LTX__is_block_mode();
extern ofb_LTX__is_block_algorithm_mode();
extern ofb_LTX__mcrypt_get_modes_name();
extern ofb_LTX__mcrypt_mode_get_size();
extern ofb_LTX__mcrypt_mode_version();
extern stream_LTX__init_mcrypt();
extern stream_LTX__mcrypt_set_state();
extern stream_LTX__mcrypt_get_state();
extern stream_LTX__end_mcrypt();
extern stream_LTX__mcrypt();
extern stream_LTX__mdecrypt();
extern stream_LTX__has_iv();
extern stream_LTX__is_block_mode();
extern stream_LTX__is_block_algorithm_mode();
extern stream_LTX__mcrypt_get_modes_name();
extern stream_LTX__mcrypt_mode_get_size();
extern stream_LTX__mcrypt_mode_version();
extern cast_128_LTX__mcrypt_set_key();
extern cast_128_LTX__mcrypt_encrypt();
extern cast_128_LTX__mcrypt_decrypt();
extern cast_128_LTX__mcrypt_get_size();
extern cast_128_LTX__mcrypt_get_block_size();
extern cast_128_LTX__is_block_algorithm();
extern cast_128_LTX__mcrypt_get_key_size();
extern cast_128_LTX__mcrypt_get_supported_key_sizes();
extern cast_128_LTX__mcrypt_get_algorithms_name();
extern cast_128_LTX__mcrypt_self_test();
extern cast_128_LTX__mcrypt_algorithm_version();
extern gost_LTX__mcrypt_set_key();
extern gost_LTX__mcrypt_encrypt();
extern gost_LTX__mcrypt_decrypt();
extern gost_LTX__mcrypt_get_size();
extern gost_LTX__mcrypt_get_block_size();
extern gost_LTX__is_block_algorithm();
extern gost_LTX__mcrypt_get_key_size();
extern gost_LTX__mcrypt_get_supported_key_sizes();
extern gost_LTX__mcrypt_get_algorithms_name();
extern gost_LTX__mcrypt_self_test();
extern gost_LTX__mcrypt_algorithm_version();
extern rijndael_128_LTX__mcrypt_set_key();
extern rijndael_128_LTX__mcrypt_encrypt();
extern rijndael_128_LTX__mcrypt_decrypt();
extern rijndael_128_LTX__mcrypt_get_size();
extern rijndael_128_LTX__mcrypt_get_block_size();
extern rijndael_128_LTX__is_block_algorithm();
extern rijndael_128_LTX__mcrypt_get_key_size();
extern rijndael_128_LTX__mcrypt_get_supported_key_sizes();
extern rijndael_128_LTX__mcrypt_get_algorithms_name();
extern rijndael_128_LTX__mcrypt_self_test();
extern rijndael_128_LTX__mcrypt_algorithm_version();
extern twofish_LTX__mcrypt_set_key();
extern twofish_LTX__mcrypt_encrypt();
extern twofish_LTX__mcrypt_decrypt();
extern twofish_LTX__mcrypt_get_size();
extern twofish_LTX__mcrypt_get_block_size();
extern twofish_LTX__is_block_algorithm();
extern twofish_LTX__mcrypt_get_key_size();
extern twofish_LTX__mcrypt_get_supported_key_sizes();
extern twofish_LTX__mcrypt_get_algorithms_name();
extern twofish_LTX__mcrypt_self_test();
extern twofish_LTX__mcrypt_algorithm_version();
extern arcfour_LTX__mcrypt_set_key();
extern arcfour_LTX__mcrypt_encrypt();
extern arcfour_LTX__mcrypt_decrypt();
extern arcfour_LTX__mcrypt_get_size();
extern arcfour_LTX__mcrypt_get_block_size();
extern arcfour_LTX__is_block_algorithm();
extern arcfour_LTX__mcrypt_get_key_size();
extern arcfour_LTX__mcrypt_get_algo_iv_size();
extern arcfour_LTX__mcrypt_get_supported_key_sizes();
extern arcfour_LTX__mcrypt_get_algorithms_name();
extern arcfour_LTX__mcrypt_self_test();
extern arcfour_LTX__mcrypt_algorithm_version();
extern cast_256_LTX__mcrypt_set_key();
extern cast_256_LTX__mcrypt_encrypt();
extern cast_256_LTX__mcrypt_decrypt();
extern cast_256_LTX__mcrypt_get_size();
extern cast_256_LTX__mcrypt_get_block_size();
extern cast_256_LTX__is_block_algorithm();
extern cast_256_LTX__mcrypt_get_key_size();
extern cast_256_LTX__mcrypt_get_supported_key_sizes();
extern cast_256_LTX__mcrypt_get_algorithms_name();
extern cast_256_LTX__mcrypt_self_test();
extern cast_256_LTX__mcrypt_algorithm_version();
extern loki97_LTX__mcrypt_set_key();
extern loki97_LTX__mcrypt_encrypt();
extern loki97_LTX__mcrypt_decrypt();
extern loki97_LTX__mcrypt_get_size();
extern loki97_LTX__mcrypt_get_block_size();
extern loki97_LTX__is_block_algorithm();
extern loki97_LTX__mcrypt_get_key_size();
extern loki97_LTX__mcrypt_get_supported_key_sizes();
extern loki97_LTX__mcrypt_get_algorithms_name();
extern loki97_LTX__mcrypt_self_test();
extern loki97_LTX__mcrypt_algorithm_version();
extern rijndael_192_LTX__mcrypt_set_key();
extern rijndael_192_LTX__mcrypt_encrypt();
extern rijndael_192_LTX__mcrypt_decrypt();
extern rijndael_192_LTX__mcrypt_get_size();
extern rijndael_192_LTX__mcrypt_get_block_size();
extern rijndael_192_LTX__is_block_algorithm();
extern rijndael_192_LTX__mcrypt_get_key_size();
extern rijndael_192_LTX__mcrypt_get_supported_key_sizes();
extern rijndael_192_LTX__mcrypt_get_algorithms_name();
extern rijndael_192_LTX__mcrypt_self_test();
extern rijndael_192_LTX__mcrypt_algorithm_version();
extern saferplus_LTX__mcrypt_set_key();
extern saferplus_LTX__mcrypt_encrypt();
extern saferplus_LTX__mcrypt_decrypt();
extern saferplus_LTX__mcrypt_get_size();
extern saferplus_LTX__mcrypt_get_block_size();
extern saferplus_LTX__is_block_algorithm();
extern saferplus_LTX__mcrypt_get_key_size();
extern saferplus_LTX__mcrypt_get_supported_key_sizes();
extern saferplus_LTX__mcrypt_get_algorithms_name();
extern saferplus_LTX__mcrypt_self_test();
extern saferplus_LTX__mcrypt_algorithm_version();
extern wake_LTX__mcrypt_set_key();
extern wake_LTX__mcrypt_encrypt();
extern wake_LTX__mcrypt_decrypt();
extern wake_LTX__mcrypt_get_size();
extern wake_LTX__mcrypt_get_block_size();
extern wake_LTX__is_block_algorithm();
extern wake_LTX__mcrypt_get_key_size();
extern wake_LTX__mcrypt_get_algo_iv_size();
extern wake_LTX__mcrypt_get_supported_key_sizes();
extern wake_LTX__mcrypt_get_algorithms_name();
extern wake_LTX__mcrypt_self_test();
extern wake_LTX__mcrypt_algorithm_version();
extern blowfish_compat_LTX__mcrypt_set_key();
extern blowfish_compat_LTX__mcrypt_encrypt();
extern blowfish_compat_LTX__mcrypt_decrypt();
extern blowfish_compat_LTX__mcrypt_get_size();
extern blowfish_compat_LTX__mcrypt_get_block_size();
extern blowfish_compat_LTX__is_block_algorithm();
extern blowfish_compat_LTX__mcrypt_get_key_size();
extern blowfish_compat_LTX__mcrypt_get_supported_key_sizes();
extern blowfish_compat_LTX__mcrypt_get_algorithms_name();
extern blowfish_compat_LTX__mcrypt_self_test();
extern blowfish_compat_LTX__mcrypt_algorithm_version();
extern des_LTX__mcrypt_set_key();
extern des_LTX__mcrypt_encrypt();
extern des_LTX__mcrypt_decrypt();
extern des_LTX__mcrypt_get_size();
extern des_LTX__mcrypt_get_block_size();
extern des_LTX__is_block_algorithm();
extern des_LTX__mcrypt_get_key_size();
extern des_LTX__mcrypt_get_supported_key_sizes();
extern des_LTX__mcrypt_get_algorithms_name();
extern des_LTX__mcrypt_self_test();
extern des_LTX__mcrypt_algorithm_version();
extern rijndael_256_LTX__mcrypt_set_key();
extern rijndael_256_LTX__mcrypt_encrypt();
extern rijndael_256_LTX__mcrypt_decrypt();
extern rijndael_256_LTX__mcrypt_get_size();
extern rijndael_256_LTX__mcrypt_get_block_size();
extern rijndael_256_LTX__is_block_algorithm();
extern rijndael_256_LTX__mcrypt_get_key_size();
extern rijndael_256_LTX__mcrypt_get_supported_key_sizes();
extern rijndael_256_LTX__mcrypt_get_algorithms_name();
extern rijndael_256_LTX__mcrypt_self_test();
extern rijndael_256_LTX__mcrypt_algorithm_version();
extern serpent_LTX__mcrypt_set_key();
extern serpent_LTX__mcrypt_encrypt();
extern serpent_LTX__mcrypt_decrypt();
extern serpent_LTX__mcrypt_get_size();
extern serpent_LTX__mcrypt_get_block_size();
extern serpent_LTX__is_block_algorithm();
extern serpent_LTX__mcrypt_get_key_size();
extern serpent_LTX__mcrypt_get_supported_key_sizes();
extern serpent_LTX__mcrypt_get_algorithms_name();
extern serpent_LTX__mcrypt_self_test();
extern serpent_LTX__mcrypt_algorithm_version();
extern xtea_LTX__mcrypt_set_key();
extern xtea_LTX__mcrypt_encrypt();
extern xtea_LTX__mcrypt_decrypt();
extern xtea_LTX__mcrypt_get_size();
extern xtea_LTX__mcrypt_get_block_size();
extern xtea_LTX__is_block_algorithm();
extern xtea_LTX__mcrypt_get_key_size();
extern xtea_LTX__mcrypt_get_supported_key_sizes();
extern xtea_LTX__mcrypt_get_algorithms_name();
extern xtea_LTX__mcrypt_self_test();
extern xtea_LTX__mcrypt_algorithm_version();
extern blowfish_LTX__mcrypt_set_key();
extern blowfish_LTX__mcrypt_encrypt();
extern blowfish_LTX__mcrypt_decrypt();
extern blowfish_LTX__mcrypt_get_size();
extern blowfish_LTX__mcrypt_get_block_size();
extern blowfish_LTX__is_block_algorithm();
extern blowfish_LTX__mcrypt_get_key_size();
extern blowfish_LTX__mcrypt_get_supported_key_sizes();
extern blowfish_LTX__mcrypt_get_algorithms_name();
extern blowfish_LTX__mcrypt_self_test();
extern blowfish_LTX__mcrypt_algorithm_version();
extern enigma_LTX__mcrypt_set_key();
extern enigma_LTX__mcrypt_encrypt();
extern enigma_LTX__mcrypt_decrypt();
extern enigma_LTX__mcrypt_get_size();
extern enigma_LTX__mcrypt_get_block_size();
extern enigma_LTX__is_block_algorithm();
extern enigma_LTX__mcrypt_get_key_size();
extern enigma_LTX__mcrypt_get_algo_iv_size();
extern enigma_LTX__mcrypt_get_supported_key_sizes();
extern enigma_LTX__mcrypt_get_algorithms_name();
extern enigma_LTX__mcrypt_self_test();
extern enigma_LTX__mcrypt_algorithm_version();
extern rc2_LTX__mcrypt_set_key();
extern rc2_LTX__mcrypt_encrypt();
extern rc2_LTX__mcrypt_decrypt();
extern rc2_LTX__mcrypt_get_size();
extern rc2_LTX__mcrypt_get_block_size();
extern rc2_LTX__is_block_algorithm();
extern rc2_LTX__mcrypt_get_key_size();
extern rc2_LTX__mcrypt_get_supported_key_sizes();
extern rc2_LTX__mcrypt_get_algorithms_name();
extern rc2_LTX__mcrypt_self_test();
extern rc2_LTX__mcrypt_algorithm_version();
extern tripledes_LTX__mcrypt_set_key();
extern tripledes_LTX__mcrypt_encrypt();
extern tripledes_LTX__mcrypt_decrypt();
extern tripledes_LTX__mcrypt_get_size();
extern tripledes_LTX__mcrypt_get_block_size();
extern tripledes_LTX__is_block_algorithm();
extern tripledes_LTX__mcrypt_get_key_size();
extern tripledes_LTX__mcrypt_get_supported_key_sizes();
extern tripledes_LTX__mcrypt_get_algorithms_name();
extern tripledes_LTX__mcrypt_self_test();
extern tripledes_LTX__mcrypt_algorithm_version();

const mcrypt_preloaded mps[] = {
	{"cbc", NULL}, 
	{"cbc_LTX__init_mcrypt", cbc_LTX__init_mcrypt},
	{"cbc_LTX__mcrypt_set_state", cbc_LTX__mcrypt_set_state},
	{"cbc_LTX__mcrypt_get_state", cbc_LTX__mcrypt_get_state},
	{"cbc_LTX__end_mcrypt", cbc_LTX__end_mcrypt},
	{"cbc_LTX__mcrypt", cbc_LTX__mcrypt},
	{"cbc_LTX__mdecrypt", cbc_LTX__mdecrypt},
	{"cbc_LTX__has_iv", cbc_LTX__has_iv},
	{"cbc_LTX__is_block_mode", cbc_LTX__is_block_mode},
	{"cbc_LTX__is_block_algorithm_mode", cbc_LTX__is_block_algorithm_mode},
	{"cbc_LTX__mcrypt_get_modes_name", cbc_LTX__mcrypt_get_modes_name},
	{"cbc_LTX__mcrypt_mode_get_size", cbc_LTX__mcrypt_mode_get_size},
	{"cbc_LTX__mcrypt_mode_version", cbc_LTX__mcrypt_mode_version},
	{"cfb", NULL}, 
	{"cfb_LTX__init_mcrypt", cfb_LTX__init_mcrypt},
	{"cfb_LTX__mcrypt_set_state", cfb_LTX__mcrypt_set_state},
	{"cfb_LTX__mcrypt_get_state", cfb_LTX__mcrypt_get_state},
	{"cfb_LTX__end_mcrypt", cfb_LTX__end_mcrypt},
	{"cfb_LTX__mcrypt", cfb_LTX__mcrypt},
	{"cfb_LTX__mdecrypt", cfb_LTX__mdecrypt},
	{"cfb_LTX__has_iv", cfb_LTX__has_iv},
	{"cfb_LTX__is_block_mode", cfb_LTX__is_block_mode},
	{"cfb_LTX__is_block_algorithm_mode", cfb_LTX__is_block_algorithm_mode},
	{"cfb_LTX__mcrypt_get_modes_name", cfb_LTX__mcrypt_get_modes_name},
	{"cfb_LTX__mcrypt_mode_get_size", cfb_LTX__mcrypt_mode_get_size},
	{"cfb_LTX__mcrypt_mode_version", cfb_LTX__mcrypt_mode_version},
	{"ctr", NULL}, 
	{"ctr_LTX__init_mcrypt", ctr_LTX__init_mcrypt},
	{"ctr_LTX__mcrypt_set_state", ctr_LTX__mcrypt_set_state},
	{"ctr_LTX__mcrypt_get_state", ctr_LTX__mcrypt_get_state},
	{"ctr_LTX__end_mcrypt", ctr_LTX__end_mcrypt},
	{"ctr_LTX__mcrypt", ctr_LTX__mcrypt},
	{"ctr_LTX__mdecrypt", ctr_LTX__mdecrypt},
	{"ctr_LTX__has_iv", ctr_LTX__has_iv},
	{"ctr_LTX__is_block_mode", ctr_LTX__is_block_mode},
	{"ctr_LTX__is_block_algorithm_mode", ctr_LTX__is_block_algorithm_mode},
	{"ctr_LTX__mcrypt_get_modes_name", ctr_LTX__mcrypt_get_modes_name},
	{"ctr_LTX__mcrypt_mode_get_size", ctr_LTX__mcrypt_mode_get_size},
	{"ctr_LTX__mcrypt_mode_version", ctr_LTX__mcrypt_mode_version},
	{"ecb", NULL}, 
	{"ecb_LTX__mcrypt_set_state", ecb_LTX__mcrypt_set_state},
	{"ecb_LTX__mcrypt_get_state", ecb_LTX__mcrypt_get_state},
	{"ecb_LTX__init_mcrypt", ecb_LTX__init_mcrypt},
	{"ecb_LTX__end_mcrypt", ecb_LTX__end_mcrypt},
	{"ecb_LTX__mcrypt", ecb_LTX__mcrypt},
	{"ecb_LTX__mdecrypt", ecb_LTX__mdecrypt},
	{"ecb_LTX__has_iv", ecb_LTX__has_iv},
	{"ecb_LTX__is_block_mode", ecb_LTX__is_block_mode},
	{"ecb_LTX__is_block_algorithm_mode", ecb_LTX__is_block_algorithm_mode},
	{"ecb_LTX__mcrypt_get_modes_name", ecb_LTX__mcrypt_get_modes_name},
	{"ecb_LTX__mcrypt_mode_get_size", ecb_LTX__mcrypt_mode_get_size},
	{"ecb_LTX__mcrypt_mode_version", ecb_LTX__mcrypt_mode_version},
	{"ncfb", NULL}, 
	{"ncfb_LTX__init_mcrypt", ncfb_LTX__init_mcrypt},
	{"ncfb_LTX__mcrypt_set_state", ncfb_LTX__mcrypt_set_state},
	{"ncfb_LTX__mcrypt_get_state", ncfb_LTX__mcrypt_get_state},
	{"ncfb_LTX__end_mcrypt", ncfb_LTX__end_mcrypt},
	{"ncfb_LTX__mcrypt", ncfb_LTX__mcrypt},
	{"ncfb_LTX__mdecrypt", ncfb_LTX__mdecrypt},
	{"ncfb_LTX__has_iv", ncfb_LTX__has_iv},
	{"ncfb_LTX__is_block_mode", ncfb_LTX__is_block_mode},
	{"ncfb_LTX__is_block_algorithm_mode", ncfb_LTX__is_block_algorithm_mode},
	{"ncfb_LTX__mcrypt_get_modes_name", ncfb_LTX__mcrypt_get_modes_name},
	{"ncfb_LTX__mcrypt_mode_get_size", ncfb_LTX__mcrypt_mode_get_size},
	{"ncfb_LTX__mcrypt_mode_version", ncfb_LTX__mcrypt_mode_version},
	{"nofb", NULL}, 
	{"nofb_LTX__init_mcrypt", nofb_LTX__init_mcrypt},
	{"nofb_LTX__mcrypt_set_state", nofb_LTX__mcrypt_set_state},
	{"nofb_LTX__mcrypt_get_state", nofb_LTX__mcrypt_get_state},
	{"nofb_LTX__end_mcrypt", nofb_LTX__end_mcrypt},
	{"nofb_LTX__mcrypt", nofb_LTX__mcrypt},
	{"nofb_LTX__mdecrypt", nofb_LTX__mdecrypt},
	{"nofb_LTX__has_iv", nofb_LTX__has_iv},
	{"nofb_LTX__is_block_mode", nofb_LTX__is_block_mode},
	{"nofb_LTX__is_block_algorithm_mode", nofb_LTX__is_block_algorithm_mode},
	{"nofb_LTX__mcrypt_get_modes_name", nofb_LTX__mcrypt_get_modes_name},
	{"nofb_LTX__mcrypt_mode_get_size", nofb_LTX__mcrypt_mode_get_size},
	{"nofb_LTX__mcrypt_mode_version", nofb_LTX__mcrypt_mode_version},
	{"ofb", NULL}, 
	{"ofb_LTX__init_mcrypt", ofb_LTX__init_mcrypt},
	{"ofb_LTX__mcrypt_set_state", ofb_LTX__mcrypt_set_state},
	{"ofb_LTX__mcrypt_get_state", ofb_LTX__mcrypt_get_state},
	{"ofb_LTX__end_mcrypt", ofb_LTX__end_mcrypt},
	{"ofb_LTX__mcrypt", ofb_LTX__mcrypt},
	{"ofb_LTX__mdecrypt", ofb_LTX__mdecrypt},
	{"ofb_LTX__has_iv", ofb_LTX__has_iv},
	{"ofb_LTX__is_block_mode", ofb_LTX__is_block_mode},
	{"ofb_LTX__is_block_algorithm_mode", ofb_LTX__is_block_algorithm_mode},
	{"ofb_LTX__mcrypt_get_modes_name", ofb_LTX__mcrypt_get_modes_name},
	{"ofb_LTX__mcrypt_mode_get_size", ofb_LTX__mcrypt_mode_get_size},
	{"ofb_LTX__mcrypt_mode_version", ofb_LTX__mcrypt_mode_version},
	{"stream", NULL}, 
	{"stream_LTX__init_mcrypt", stream_LTX__init_mcrypt},
	{"stream_LTX__mcrypt_set_state", stream_LTX__mcrypt_set_state},
	{"stream_LTX__mcrypt_get_state", stream_LTX__mcrypt_get_state},
	{"stream_LTX__end_mcrypt", stream_LTX__end_mcrypt},
	{"stream_LTX__mcrypt", stream_LTX__mcrypt},
	{"stream_LTX__mdecrypt", stream_LTX__mdecrypt},
	{"stream_LTX__has_iv", stream_LTX__has_iv},
	{"stream_LTX__is_block_mode", stream_LTX__is_block_mode},
	{"stream_LTX__is_block_algorithm_mode", stream_LTX__is_block_algorithm_mode},
	{"stream_LTX__mcrypt_get_modes_name", stream_LTX__mcrypt_get_modes_name},
	{"stream_LTX__mcrypt_mode_get_size", stream_LTX__mcrypt_mode_get_size},
	{"stream_LTX__mcrypt_mode_version", stream_LTX__mcrypt_mode_version},
	{"cast-128", NULL}, 
	{"cast_128_LTX__mcrypt_set_key", cast_128_LTX__mcrypt_set_key},
	{"cast_128_LTX__mcrypt_encrypt", cast_128_LTX__mcrypt_encrypt},
	{"cast_128_LTX__mcrypt_decrypt", cast_128_LTX__mcrypt_decrypt},
	{"cast_128_LTX__mcrypt_get_size", cast_128_LTX__mcrypt_get_size},
	{"cast_128_LTX__mcrypt_get_block_size", cast_128_LTX__mcrypt_get_block_size},
	{"cast_128_LTX__is_block_algorithm", cast_128_LTX__is_block_algorithm},
	{"cast_128_LTX__mcrypt_get_key_size", cast_128_LTX__mcrypt_get_key_size},
	{"cast_128_LTX__mcrypt_get_supported_key_sizes", cast_128_LTX__mcrypt_get_supported_key_sizes},
	{"cast_128_LTX__mcrypt_get_algorithms_name", cast_128_LTX__mcrypt_get_algorithms_name},
	{"cast_128_LTX__mcrypt_self_test", cast_128_LTX__mcrypt_self_test},
	{"cast_128_LTX__mcrypt_algorithm_version", cast_128_LTX__mcrypt_algorithm_version},
	{"gost", NULL}, 
	{"gost_LTX__mcrypt_set_key", gost_LTX__mcrypt_set_key},
	{"gost_LTX__mcrypt_encrypt", gost_LTX__mcrypt_encrypt},
	{"gost_LTX__mcrypt_decrypt", gost_LTX__mcrypt_decrypt},
	{"gost_LTX__mcrypt_get_size", gost_LTX__mcrypt_get_size},
	{"gost_LTX__mcrypt_get_block_size", gost_LTX__mcrypt_get_block_size},
	{"gost_LTX__is_block_algorithm", gost_LTX__is_block_algorithm},
	{"gost_LTX__mcrypt_get_key_size", gost_LTX__mcrypt_get_key_size},
	{"gost_LTX__mcrypt_get_supported_key_sizes", gost_LTX__mcrypt_get_supported_key_sizes},
	{"gost_LTX__mcrypt_get_algorithms_name", gost_LTX__mcrypt_get_algorithms_name},
	{"gost_LTX__mcrypt_self_test", gost_LTX__mcrypt_self_test},
	{"gost_LTX__mcrypt_algorithm_version", gost_LTX__mcrypt_algorithm_version},
	{"rijndael-128", NULL}, 
	{"rijndael_128_LTX__mcrypt_set_key", rijndael_128_LTX__mcrypt_set_key},
	{"rijndael_128_LTX__mcrypt_encrypt", rijndael_128_LTX__mcrypt_encrypt},
	{"rijndael_128_LTX__mcrypt_decrypt", rijndael_128_LTX__mcrypt_decrypt},
	{"rijndael_128_LTX__mcrypt_get_size", rijndael_128_LTX__mcrypt_get_size},
	{"rijndael_128_LTX__mcrypt_get_block_size", rijndael_128_LTX__mcrypt_get_block_size},
	{"rijndael_128_LTX__is_block_algorithm", rijndael_128_LTX__is_block_algorithm},
	{"rijndael_128_LTX__mcrypt_get_key_size", rijndael_128_LTX__mcrypt_get_key_size},
	{"rijndael_128_LTX__mcrypt_get_supported_key_sizes", rijndael_128_LTX__mcrypt_get_supported_key_sizes},
	{"rijndael_128_LTX__mcrypt_get_algorithms_name", rijndael_128_LTX__mcrypt_get_algorithms_name},
	{"rijndael_128_LTX__mcrypt_self_test", rijndael_128_LTX__mcrypt_self_test},
	{"rijndael_128_LTX__mcrypt_algorithm_version", rijndael_128_LTX__mcrypt_algorithm_version},
	{"twofish", NULL}, 
	{"twofish_LTX__mcrypt_set_key", twofish_LTX__mcrypt_set_key},
	{"twofish_LTX__mcrypt_encrypt", twofish_LTX__mcrypt_encrypt},
	{"twofish_LTX__mcrypt_decrypt", twofish_LTX__mcrypt_decrypt},
	{"twofish_LTX__mcrypt_get_size", twofish_LTX__mcrypt_get_size},
	{"twofish_LTX__mcrypt_get_block_size", twofish_LTX__mcrypt_get_block_size},
	{"twofish_LTX__is_block_algorithm", twofish_LTX__is_block_algorithm},
	{"twofish_LTX__mcrypt_get_key_size", twofish_LTX__mcrypt_get_key_size},
	{"twofish_LTX__mcrypt_get_supported_key_sizes", twofish_LTX__mcrypt_get_supported_key_sizes},
	{"twofish_LTX__mcrypt_get_algorithms_name", twofish_LTX__mcrypt_get_algorithms_name},
	{"twofish_LTX__mcrypt_self_test", twofish_LTX__mcrypt_self_test},
	{"twofish_LTX__mcrypt_algorithm_version", twofish_LTX__mcrypt_algorithm_version},
	{"arcfour", NULL}, 
	{"arcfour_LTX__mcrypt_set_key", arcfour_LTX__mcrypt_set_key},
	{"arcfour_LTX__mcrypt_encrypt", arcfour_LTX__mcrypt_encrypt},
	{"arcfour_LTX__mcrypt_decrypt", arcfour_LTX__mcrypt_decrypt},
	{"arcfour_LTX__mcrypt_get_size", arcfour_LTX__mcrypt_get_size},
	{"arcfour_LTX__mcrypt_get_block_size", arcfour_LTX__mcrypt_get_block_size},
	{"arcfour_LTX__is_block_algorithm", arcfour_LTX__is_block_algorithm},
	{"arcfour_LTX__mcrypt_get_key_size", arcfour_LTX__mcrypt_get_key_size},
	{"arcfour_LTX__mcrypt_get_algo_iv_size", arcfour_LTX__mcrypt_get_algo_iv_size},
	{"arcfour_LTX__mcrypt_get_supported_key_sizes", arcfour_LTX__mcrypt_get_supported_key_sizes},
	{"arcfour_LTX__mcrypt_get_algorithms_name", arcfour_LTX__mcrypt_get_algorithms_name},
	{"arcfour_LTX__mcrypt_self_test", arcfour_LTX__mcrypt_self_test},
	{"arcfour_LTX__mcrypt_algorithm_version", arcfour_LTX__mcrypt_algorithm_version},
	{"cast-256", NULL}, 
	{"cast_256_LTX__mcrypt_set_key", cast_256_LTX__mcrypt_set_key},
	{"cast_256_LTX__mcrypt_encrypt", cast_256_LTX__mcrypt_encrypt},
	{"cast_256_LTX__mcrypt_decrypt", cast_256_LTX__mcrypt_decrypt},
	{"cast_256_LTX__mcrypt_get_size", cast_256_LTX__mcrypt_get_size},
	{"cast_256_LTX__mcrypt_get_block_size", cast_256_LTX__mcrypt_get_block_size},
	{"cast_256_LTX__is_block_algorithm", cast_256_LTX__is_block_algorithm},
	{"cast_256_LTX__mcrypt_get_key_size", cast_256_LTX__mcrypt_get_key_size},
	{"cast_256_LTX__mcrypt_get_supported_key_sizes", cast_256_LTX__mcrypt_get_supported_key_sizes},
	{"cast_256_LTX__mcrypt_get_algorithms_name", cast_256_LTX__mcrypt_get_algorithms_name},
	{"cast_256_LTX__mcrypt_self_test", cast_256_LTX__mcrypt_self_test},
	{"cast_256_LTX__mcrypt_algorithm_version", cast_256_LTX__mcrypt_algorithm_version},
	{"loki97", NULL}, 
	{"loki97_LTX__mcrypt_set_key", loki97_LTX__mcrypt_set_key},
	{"loki97_LTX__mcrypt_encrypt", loki97_LTX__mcrypt_encrypt},
	{"loki97_LTX__mcrypt_decrypt", loki97_LTX__mcrypt_decrypt},
	{"loki97_LTX__mcrypt_get_size", loki97_LTX__mcrypt_get_size},
	{"loki97_LTX__mcrypt_get_block_size", loki97_LTX__mcrypt_get_block_size},
	{"loki97_LTX__is_block_algorithm", loki97_LTX__is_block_algorithm},
	{"loki97_LTX__mcrypt_get_key_size", loki97_LTX__mcrypt_get_key_size},
	{"loki97_LTX__mcrypt_get_supported_key_sizes", loki97_LTX__mcrypt_get_supported_key_sizes},
	{"loki97_LTX__mcrypt_get_algorithms_name", loki97_LTX__mcrypt_get_algorithms_name},
	{"loki97_LTX__mcrypt_self_test", loki97_LTX__mcrypt_self_test},
	{"loki97_LTX__mcrypt_algorithm_version", loki97_LTX__mcrypt_algorithm_version},
	{"rijndael-192", NULL}, 
	{"rijndael_192_LTX__mcrypt_set_key", rijndael_192_LTX__mcrypt_set_key},
	{"rijndael_192_LTX__mcrypt_encrypt", rijndael_192_LTX__mcrypt_encrypt},
	{"rijndael_192_LTX__mcrypt_decrypt", rijndael_192_LTX__mcrypt_decrypt},
	{"rijndael_192_LTX__mcrypt_get_size", rijndael_192_LTX__mcrypt_get_size},
	{"rijndael_192_LTX__mcrypt_get_block_size", rijndael_192_LTX__mcrypt_get_block_size},
	{"rijndael_192_LTX__is_block_algorithm", rijndael_192_LTX__is_block_algorithm},
	{"rijndael_192_LTX__mcrypt_get_key_size", rijndael_192_LTX__mcrypt_get_key_size},
	{"rijndael_192_LTX__mcrypt_get_supported_key_sizes", rijndael_192_LTX__mcrypt_get_supported_key_sizes},
	{"rijndael_192_LTX__mcrypt_get_algorithms_name", rijndael_192_LTX__mcrypt_get_algorithms_name},
	{"rijndael_192_LTX__mcrypt_self_test", rijndael_192_LTX__mcrypt_self_test},
	{"rijndael_192_LTX__mcrypt_algorithm_version", rijndael_192_LTX__mcrypt_algorithm_version},
	{"saferplus", NULL}, 
	{"saferplus_LTX__mcrypt_set_key", saferplus_LTX__mcrypt_set_key},
	{"saferplus_LTX__mcrypt_encrypt", saferplus_LTX__mcrypt_encrypt},
	{"saferplus_LTX__mcrypt_decrypt", saferplus_LTX__mcrypt_decrypt},
	{"saferplus_LTX__mcrypt_get_size", saferplus_LTX__mcrypt_get_size},
	{"saferplus_LTX__mcrypt_get_block_size", saferplus_LTX__mcrypt_get_block_size},
	{"saferplus_LTX__is_block_algorithm", saferplus_LTX__is_block_algorithm},
	{"saferplus_LTX__mcrypt_get_key_size", saferplus_LTX__mcrypt_get_key_size},
	{"saferplus_LTX__mcrypt_get_supported_key_sizes", saferplus_LTX__mcrypt_get_supported_key_sizes},
	{"saferplus_LTX__mcrypt_get_algorithms_name", saferplus_LTX__mcrypt_get_algorithms_name},
	{"saferplus_LTX__mcrypt_self_test", saferplus_LTX__mcrypt_self_test},
	{"saferplus_LTX__mcrypt_algorithm_version", saferplus_LTX__mcrypt_algorithm_version},
	{"wake", NULL}, 
	{"wake_LTX__mcrypt_set_key", wake_LTX__mcrypt_set_key},
	{"wake_LTX__mcrypt_encrypt", wake_LTX__mcrypt_encrypt},
	{"wake_LTX__mcrypt_decrypt", wake_LTX__mcrypt_decrypt},
	{"wake_LTX__mcrypt_get_size", wake_LTX__mcrypt_get_size},
	{"wake_LTX__mcrypt_get_block_size", wake_LTX__mcrypt_get_block_size},
	{"wake_LTX__is_block_algorithm", wake_LTX__is_block_algorithm},
	{"wake_LTX__mcrypt_get_key_size", wake_LTX__mcrypt_get_key_size},
	{"wake_LTX__mcrypt_get_algo_iv_size", wake_LTX__mcrypt_get_algo_iv_size},
	{"wake_LTX__mcrypt_get_supported_key_sizes", wake_LTX__mcrypt_get_supported_key_sizes},
	{"wake_LTX__mcrypt_get_algorithms_name", wake_LTX__mcrypt_get_algorithms_name},
	{"wake_LTX__mcrypt_self_test", wake_LTX__mcrypt_self_test},
	{"wake_LTX__mcrypt_algorithm_version", wake_LTX__mcrypt_algorithm_version},
	{"blowfish-compat", NULL}, 
	{"blowfish_compat_LTX__mcrypt_set_key", blowfish_compat_LTX__mcrypt_set_key},
	{"blowfish_compat_LTX__mcrypt_encrypt", blowfish_compat_LTX__mcrypt_encrypt},
	{"blowfish_compat_LTX__mcrypt_decrypt", blowfish_compat_LTX__mcrypt_decrypt},
	{"blowfish_compat_LTX__mcrypt_get_size", blowfish_compat_LTX__mcrypt_get_size},
	{"blowfish_compat_LTX__mcrypt_get_block_size", blowfish_compat_LTX__mcrypt_get_block_size},
	{"blowfish_compat_LTX__is_block_algorithm", blowfish_compat_LTX__is_block_algorithm},
	{"blowfish_compat_LTX__mcrypt_get_key_size", blowfish_compat_LTX__mcrypt_get_key_size},
	{"blowfish_compat_LTX__mcrypt_get_supported_key_sizes", blowfish_compat_LTX__mcrypt_get_supported_key_sizes},
	{"blowfish_compat_LTX__mcrypt_get_algorithms_name", blowfish_compat_LTX__mcrypt_get_algorithms_name},
	{"blowfish_compat_LTX__mcrypt_self_test", blowfish_compat_LTX__mcrypt_self_test},
	{"blowfish_compat_LTX__mcrypt_algorithm_version", blowfish_compat_LTX__mcrypt_algorithm_version},
	{"des", NULL}, 
	{"des_LTX__mcrypt_set_key", des_LTX__mcrypt_set_key},
	{"des_LTX__mcrypt_encrypt", des_LTX__mcrypt_encrypt},
	{"des_LTX__mcrypt_decrypt", des_LTX__mcrypt_decrypt},
	{"des_LTX__mcrypt_get_size", des_LTX__mcrypt_get_size},
	{"des_LTX__mcrypt_get_block_size", des_LTX__mcrypt_get_block_size},
	{"des_LTX__is_block_algorithm", des_LTX__is_block_algorithm},
	{"des_LTX__mcrypt_get_key_size", des_LTX__mcrypt_get_key_size},
	{"des_LTX__mcrypt_get_supported_key_sizes", des_LTX__mcrypt_get_supported_key_sizes},
	{"des_LTX__mcrypt_get_algorithms_name", des_LTX__mcrypt_get_algorithms_name},
	{"des_LTX__mcrypt_self_test", des_LTX__mcrypt_self_test},
	{"des_LTX__mcrypt_algorithm_version", des_LTX__mcrypt_algorithm_version},
	{"rijndael-256", NULL}, 
	{"rijndael_256_LTX__mcrypt_set_key", rijndael_256_LTX__mcrypt_set_key},
	{"rijndael_256_LTX__mcrypt_encrypt", rijndael_256_LTX__mcrypt_encrypt},
	{"rijndael_256_LTX__mcrypt_decrypt", rijndael_256_LTX__mcrypt_decrypt},
	{"rijndael_256_LTX__mcrypt_get_size", rijndael_256_LTX__mcrypt_get_size},
	{"rijndael_256_LTX__mcrypt_get_block_size", rijndael_256_LTX__mcrypt_get_block_size},
	{"rijndael_256_LTX__is_block_algorithm", rijndael_256_LTX__is_block_algorithm},
	{"rijndael_256_LTX__mcrypt_get_key_size", rijndael_256_LTX__mcrypt_get_key_size},
	{"rijndael_256_LTX__mcrypt_get_supported_key_sizes", rijndael_256_LTX__mcrypt_get_supported_key_sizes},
	{"rijndael_256_LTX__mcrypt_get_algorithms_name", rijndael_256_LTX__mcrypt_get_algorithms_name},
	{"rijndael_256_LTX__mcrypt_self_test", rijndael_256_LTX__mcrypt_self_test},
	{"rijndael_256_LTX__mcrypt_algorithm_version", rijndael_256_LTX__mcrypt_algorithm_version},
	{"serpent", NULL}, 
	{"serpent_LTX__mcrypt_set_key", serpent_LTX__mcrypt_set_key},
	{"serpent_LTX__mcrypt_encrypt", serpent_LTX__mcrypt_encrypt},
	{"serpent_LTX__mcrypt_decrypt", serpent_LTX__mcrypt_decrypt},
	{"serpent_LTX__mcrypt_get_size", serpent_LTX__mcrypt_get_size},
	{"serpent_LTX__mcrypt_get_block_size", serpent_LTX__mcrypt_get_block_size},
	{"serpent_LTX__is_block_algorithm", serpent_LTX__is_block_algorithm},
	{"serpent_LTX__mcrypt_get_key_size", serpent_LTX__mcrypt_get_key_size},
	{"serpent_LTX__mcrypt_get_supported_key_sizes", serpent_LTX__mcrypt_get_supported_key_sizes},
	{"serpent_LTX__mcrypt_get_algorithms_name", serpent_LTX__mcrypt_get_algorithms_name},
	{"serpent_LTX__mcrypt_self_test", serpent_LTX__mcrypt_self_test},
	{"serpent_LTX__mcrypt_algorithm_version", serpent_LTX__mcrypt_algorithm_version},
	{"xtea", NULL}, 
	{"xtea_LTX__mcrypt_set_key", xtea_LTX__mcrypt_set_key},
	{"xtea_LTX__mcrypt_encrypt", xtea_LTX__mcrypt_encrypt},
	{"xtea_LTX__mcrypt_decrypt", xtea_LTX__mcrypt_decrypt},
	{"xtea_LTX__mcrypt_get_size", xtea_LTX__mcrypt_get_size},
	{"xtea_LTX__mcrypt_get_block_size", xtea_LTX__mcrypt_get_block_size},
	{"xtea_LTX__is_block_algorithm", xtea_LTX__is_block_algorithm},
	{"xtea_LTX__mcrypt_get_key_size", xtea_LTX__mcrypt_get_key_size},
	{"xtea_LTX__mcrypt_get_supported_key_sizes", xtea_LTX__mcrypt_get_supported_key_sizes},
	{"xtea_LTX__mcrypt_get_algorithms_name", xtea_LTX__mcrypt_get_algorithms_name},
	{"xtea_LTX__mcrypt_self_test", xtea_LTX__mcrypt_self_test},
	{"xtea_LTX__mcrypt_algorithm_version", xtea_LTX__mcrypt_algorithm_version},
	{"blowfish", NULL}, 
	{"blowfish_LTX__mcrypt_set_key", blowfish_LTX__mcrypt_set_key},
	{"blowfish_LTX__mcrypt_encrypt", blowfish_LTX__mcrypt_encrypt},
	{"blowfish_LTX__mcrypt_decrypt", blowfish_LTX__mcrypt_decrypt},
	{"blowfish_LTX__mcrypt_get_size", blowfish_LTX__mcrypt_get_size},
	{"blowfish_LTX__mcrypt_get_block_size", blowfish_LTX__mcrypt_get_block_size},
	{"blowfish_LTX__is_block_algorithm", blowfish_LTX__is_block_algorithm},
	{"blowfish_LTX__mcrypt_get_key_size", blowfish_LTX__mcrypt_get_key_size},
	{"blowfish_LTX__mcrypt_get_supported_key_sizes", blowfish_LTX__mcrypt_get_supported_key_sizes},
	{"blowfish_LTX__mcrypt_get_algorithms_name", blowfish_LTX__mcrypt_get_algorithms_name},
	{"blowfish_LTX__mcrypt_self_test", blowfish_LTX__mcrypt_self_test},
	{"blowfish_LTX__mcrypt_algorithm_version", blowfish_LTX__mcrypt_algorithm_version},
	{"enigma", NULL}, 
	{"enigma_LTX__mcrypt_set_key", enigma_LTX__mcrypt_set_key},
	{"enigma_LTX__mcrypt_encrypt", enigma_LTX__mcrypt_encrypt},
	{"enigma_LTX__mcrypt_decrypt", enigma_LTX__mcrypt_decrypt},
	{"enigma_LTX__mcrypt_get_size", enigma_LTX__mcrypt_get_size},
	{"enigma_LTX__mcrypt_get_block_size", enigma_LTX__mcrypt_get_block_size},
	{"enigma_LTX__is_block_algorithm", enigma_LTX__is_block_algorithm},
	{"enigma_LTX__mcrypt_get_key_size", enigma_LTX__mcrypt_get_key_size},
	{"enigma_LTX__mcrypt_get_algo_iv_size", enigma_LTX__mcrypt_get_algo_iv_size},
	{"enigma_LTX__mcrypt_get_supported_key_sizes", enigma_LTX__mcrypt_get_supported_key_sizes},
	{"enigma_LTX__mcrypt_get_algorithms_name", enigma_LTX__mcrypt_get_algorithms_name},
	{"enigma_LTX__mcrypt_self_test", enigma_LTX__mcrypt_self_test},
	{"enigma_LTX__mcrypt_algorithm_version", enigma_LTX__mcrypt_algorithm_version},
	{"rc2", NULL}, 
	{"rc2_LTX__mcrypt_set_key", rc2_LTX__mcrypt_set_key},
	{"rc2_LTX__mcrypt_encrypt", rc2_LTX__mcrypt_encrypt},
	{"rc2_LTX__mcrypt_decrypt", rc2_LTX__mcrypt_decrypt},
	{"rc2_LTX__mcrypt_get_size", rc2_LTX__mcrypt_get_size},
	{"rc2_LTX__mcrypt_get_block_size", rc2_LTX__mcrypt_get_block_size},
	{"rc2_LTX__is_block_algorithm", rc2_LTX__is_block_algorithm},
	{"rc2_LTX__mcrypt_get_key_size", rc2_LTX__mcrypt_get_key_size},
	{"rc2_LTX__mcrypt_get_supported_key_sizes", rc2_LTX__mcrypt_get_supported_key_sizes},
	{"rc2_LTX__mcrypt_get_algorithms_name", rc2_LTX__mcrypt_get_algorithms_name},
	{"rc2_LTX__mcrypt_self_test", rc2_LTX__mcrypt_self_test},
	{"rc2_LTX__mcrypt_algorithm_version", rc2_LTX__mcrypt_algorithm_version},
	{"tripledes", NULL}, 
	{"tripledes_LTX__mcrypt_set_key", tripledes_LTX__mcrypt_set_key},
	{"tripledes_LTX__mcrypt_encrypt", tripledes_LTX__mcrypt_encrypt},
	{"tripledes_LTX__mcrypt_decrypt", tripledes_LTX__mcrypt_decrypt},
	{"tripledes_LTX__mcrypt_get_size", tripledes_LTX__mcrypt_get_size},
	{"tripledes_LTX__mcrypt_get_block_size", tripledes_LTX__mcrypt_get_block_size},
	{"tripledes_LTX__is_block_algorithm", tripledes_LTX__is_block_algorithm},
	{"tripledes_LTX__mcrypt_get_key_size", tripledes_LTX__mcrypt_get_key_size},
	{"tripledes_LTX__mcrypt_get_supported_key_sizes", tripledes_LTX__mcrypt_get_supported_key_sizes},
	{"tripledes_LTX__mcrypt_get_algorithms_name", tripledes_LTX__mcrypt_get_algorithms_name},
	{"tripledes_LTX__mcrypt_self_test", tripledes_LTX__mcrypt_self_test},
	{"tripledes_LTX__mcrypt_algorithm_version", tripledes_LTX__mcrypt_algorithm_version},
	{NULL, NULL}
};
