# Copyright 2012 Google Inc. All Rights Reserved.
#
# Description:
#  PHP is an HTML-embedded scripting language. Much of its syntax is borrowed
#  from C, Java and Perl with a couple of unique PHP-specific features thrown
#  in. The goal of the language is to allow web developers to write dynamically
#  generated pages quickly.

licenses(['notice'])  # PHP License 3.01

exports_files(['LICENSE'])

package(default_visibility = ['//visibility:public'])
